apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: imagenet
spec:
  slotsPerWorker: 8
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: artifactory.tusimple.ai/docker-rnd/cxt/pipeline-base-lidar0108/cuda10.0-cudnn7:nccl
             name: imagenet
             command:
             - /root/3rdparty/openmpi4.0/bin/mpirun
             - --allow-run-as-root
             - -np
             - "8"
             - -bind-to
             - none
             - -map-by
             - slot
             - -x
             - NCCL_DEBUG=INFO
             - -x
             - NCCL_SHM_DISABLE=1
             - -x
             - LD_LIBRARY_PATH
             - -x
             - PATH
             - -x
             - OMP_NUM_THREADS=1
             - -mca
             - pml
             - ob1
             - -mca
             - btl
             - ^openib
             - bash
             - ./scripts/train_imagenet.sh
             workingDir: /mnt/truenas/upload/xiaotao.chen/Repositories/resnet.mxnet
           imagePullSecrets:
             - name: artifactory

    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - image: artifactory.tusimple.ai/docker-rnd/cxt/pipeline-base-lidar0108/cuda10.0-cudnn7:nccl
            name: imagenet
            resources:
              limits:
                nvidia.com/gpu: 8
            volumeMounts:
            - mountPath: /mnt
              name: vol1

          volumes:
          - hostPath:
              path: /mnt
              type: ""
            name: vol1
          imagePullSecrets:
             - name: artifactory
